name: erikberglund.github.io
description: Adventures in Code
meta_description: "Erik Berglund"

aboutPage: true

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge

# Gems
plugins: [jekyll-paginate]

paginate: 20
baseurl: /project
domain_name: 'http://erikberglund.github.io'
google_analytics: 'UA-75593310-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://erikberglund.github.io'
author:         'Erik Berglund'
authorTwitter:  'ekkrik'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
